repository_type: pipeline
nf_core_version: 4.1.0
lint:
  files_unchanged:
    - assets/sendmail_template.txt
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - .github/workflows/linting_comment.yml
  schema_params: false
template:
  org: nf-core
  name: daamicrobiome
  description: Microbiome differential abundance consensus pipeline
  author: Martina Cardinali
  version: 1.0.0dev
  force: true
  outdir: nf-core-daamicrobiome
  skip_features:
    - igenomes
    - fastqc
    - multiqc
  is_nfcore: true
